# Generated by Django 5.1.1 on 2024-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udtApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=255)),
                ('time_index', models.DateTimeField()),
                ('trafficflow', models.IntegerField()),
            ],
            options={
                'db_table': 'mtopeniot.etdevice',
                'managed': False,
            },
        ),
    ]
