# Generated by Django 5.1.1 on 2024-09-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udtApp', '0002_misuration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='misuration',
            table='mtopeniot.ethttps://smartdatamodels.org/datamodel.transportation/roadsegm',
        ),
    ]
