# Generated by Django 5.1.1 on 2024-09-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udtApp', '0003_alter_misuration_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='misuration',
            table='mtopeniot.etdevice',
        ),
    ]
