# Generated by Django 5.1.1 on 2024-09-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udtApp', '0004_alter_misuration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_flow', models.IntegerField()),
            ],
            options={
                'db_table': 'entities',
            },
        ),
    ]
