# Generated by Django 4.1.13 on 2024-09-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udtApp', '0007_delete_entity_alter_device_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.RemoveField(
            model_name='trafficflow',
            name='md',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
        migrations.DeleteModel(
            name='TrafficFlow',
        ),
    ]
